from .user import UserViewSet
from .customtokenpairview import CustomTokenObtainPairView
from .workoutProgram import WorkoutProgramViewSet
from .weekProgram import WeekProgramViewSet
from .exercice import ExerciceViewSet
from .dayProgram import DayProgramViewSet
from .progressUser import ProgressUserViewSet
from .series import SeriesViewSet
from .performance import PerformanceViewSet