# Generated by Django 5.0.2 on 2024-02-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myGym_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayprogram',
            name='exercices',
        ),
        migrations.AddField(
            model_name='dayprogram',
            name='exercises',
            field=models.ManyToManyField(related_name='day_programs', to='myGym_data.exercice'),
        ),
    ]
